title: "Loïc Rouaud, PhD"
logo: /assets/github_portfolio_picture.jpg
description: "Portfolio: Machine Learning • Bioinformatics • NLP • MLOps"
show_downloads: true
theme: jekyll-theme-minimal
markdown: kramdown
