title: "Loïc Rouaud, PhD"
logo: "https://avatars.githubusercontent.com/u/42077711?v=4"
description: "Portfolio: Machine Learning • Bioinformatics • NLP • MLOps"
show_downloads: true
theme: jekyll-theme-minimal
markdown: kramdown
