title: "Loïc Rouaud, PhD"
#logo: /assets/img/headshot_circle.png
description: "Portfolio: Machine Learning • Bioinformatics • NLP • MLOps"
show_downloads: true
theme: jekyll-theme-minimal
markdown: kramdown
