title: "Loïc Rouaud, PhD"
logo: /assets/github_portfolio_picture.jpg
description: "Portfolio: Machine Learning • Bioinformatics • NLP • MLOps"
show_downloads: true
theme: jekyll-theme-minimal
markdown: kramdown

# Personalization
author: "Loïc Rouaud"
email: loic.rouaud@gmail.com
github_username: loicrouaud

# Social links
linkedin_username: loic-rouaud
twitter_username: loicrouaud

# Additional professional profiles
leetcode_username: mrbroma
hackerrank_username: loic_rouaud

# SEO and metadata
url: "https://loicrouaud.github.io"
baseurl: ""
google_scholar: "https://scholar.google.com/citations?user=Q4cMnWMAAAAJ&hl=en"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Includes
include:
  - assets

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# SEO Tag
title-separator: "|"
lang: en_US

# Professional information
tagline: "Biomedical Data Scientist | ML Engineer | Bioinformatics Specialist"
keywords: "data science, machine learning, bioinformatics, NLP, MLOps, Python, RNA-seq, biomedical research"
